version: '3.10'
services:
  backend:
    image: pythonproject-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    image: pythonproject-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html